queue_rules:
- name: default
  conditions:
  - status-success=brew test-bot / test-bot (ubuntu-22.04)
  - status-success=brew test-bot / test-bot (macos-13)
  - status-success=brew test-bot / test-bot (macos-14)

pull_request_rules:
- name: automatic rebase for releases
  conditions:
  - status-success=brew test-bot / test-bot (ubuntu-22.04)
  - status-success=brew test-bot / test-bot (macos-13)
  - status-success=brew test-bot / test-bot (macos-14)
  - base=main
  - label=releases
  - author=PurpleBooth
  actions:
    label:
      add:
      - pr-pull

- name: request review on external contributor
  conditions:
  - -author=PurpleBooth
  actions:
    assign:
      add_users:
      - PurpleBooth

- name: automatic rebase for dependencies
  conditions:
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    queue:
      method: rebase
      name: default
