pull_request_rules:
  - name: Trigger merge from automerge action
    conditions:
      - status-success=test-bot (ubuntu-latest)
      - status-success=test-bot (macOS-latest)
      - base=main
      - label=automerge-squash
    actions:
      review:
        message: Look's good, lets merge it!
  - name: Keep branch up to date
    conditions:
      - base=main
      - label=automerge-squash
    actions:
      update: ~
  - name: Trigger merge from automerge action
    conditions:
      - status-success=test-bot (ubuntu-latest)
      - status-success=test-bot (macOS-latest)
      - base=main
      - label=automerge-rebase
    actions:
      review:
        message: Look's good, lets merge it!
  - name: Keep branch up to date
    conditions:
      - base=main
      - label=automerge-rebase
    actions:
      update: ~
  - name: Trigger merge from automerge action
    conditions:
      - status-success=test-bot
      - base=main
      - label=releases
    actions:
      review:
        message: Look's good, lets merge it!
  - name: Keep branch up to date
    conditions:
      - base=main
      - label=releases
    actions:
      update: ~
  - name: Trigger merge from automerge action
    conditions:
      - status-success=test-bot (ubuntu-latest)
      - status-success=test-bot (macOS-latest)
      - base=main
      - label=bottles
    actions:
      review:
        message: Look's good, lets merge it!
  - name: Keep branch up to date
    conditions:
      - base=main
      - label=bottles
    actions:
      update: ~
