queue_rules:
- name: default
  conditions:
  - status-success=test-bot (ubuntu-latest)
  - status-success=test-bot (macos-latest)

pull_request_rules:
- name: automatic rebase for releases
  conditions:
  - status-success=test-bot (ubuntu-latest)
  - status-success=test-bot (macos-latest)
  - base=main
  - label=releases
  - author=PurpleBooth
  actions:
    label:
      add:
      - pr-pull

- name: request review on external contributor
  conditions:
  - -author=PurpleBooth
  actions:
    assign:
      add_users:
      - PurpleBooth

- name: automatic rebase for dependencies
  conditions:
  - status-success=test-bot (ubuntu-latest)
  - status-success=test-bot (macos-latest)
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      name: default
