pull_request_rules:
- name: automatic rebase for releases
  conditions:
  - status-success=test-bot (ubuntu-latest)
  - status-success=test-bot (macos-latest)
  - base=main
  - label=releases
  - author=PurpleBooth
  actions:
    comment:
      message: Looks good, merging
    label:
      add:
      - pr-pull
- name: automatic rebase for dependencies
  conditions:
  - status-success=test-bot (ubuntu-latest)
  - status-success=test-bot (macos-latest)
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    merge:
      strict: smart+fasttrack
      method: merge
