---
# Concourse pipeline to auto-format Homebrew formulae
# - Triggers daily and on any change to main
# - Uses the official homebrew/brew image to run `brew style --fix`
# - Commits and pushes any changes back to the repository
jobs:
  - name: set-pipeline
    serial: true
    plan:
      - get: tap-repo
        trigger: true
      - set_pipeline: self
        file: tap-repo/ci/concourse.yaml
        var_files: [tap-repo/ci/concourse-params.yaml]
  - name: validate-tap
    serial: true
    plan:
      - get: task
      - get: tap-repo
        trigger: true
        version: latest
      - get: daily
        trigger: true
      - task: brew-style-check
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: homebrew/brew
              tag: latest
          inputs:
            - name: tap-repo
          outputs:
            - name: tap-repo
          run:
            path: bash
            user: root
            dir: tap-repo
            args:
              - -xeuo
              - pipefail
              - -c
              - |
                chown -vR linuxbrew:linuxbrew *
                BREW_COMMAND="$(command -v brew)"
                su - linuxbrew -c "cd \"$(pwd)\" && \"$BREW_COMMAND\" style Formula/*.rb"
        on_failure:
          do:
            - task: brew-style-fix
              config:
                platform: linux
                image_resource:
                  type: registry-image
                  source:
                    repository: homebrew/brew
                    tag: latest
                inputs:
                  - name: tap-repo
                outputs:
                  - name: tap-repo
                params:
                  GIT_AUTHOR_NAME: ((bot.name))
                  GIT_AUTHOR_EMAIL: ((bot.email))
                run:
                  path: bash
                  user: root
                  dir: tap-repo
                  args:
                    - -xeuo
                    - pipefail
                    - -c
                    - |
                      chown -vR linuxbrew:linuxbrew *
                      BREW_COMMAND="$(command -v brew)"
                      su - linuxbrew -c "cd \"$(pwd)\" && \"$BREW_COMMAND\" style --fix Formula/*.rb"
                      chown -vR root:root *
            - task: git-commit
              file: task/concourse/tasks/git/commit.yaml
              input_mapping:
                src: tap-repo
              output_mapping:
                src: tap-repo
              params:
                ADD: .
                MESSAGE: 'style(brew): apply auto-fixes'
                GIT_COMMITTER_NAME: ((bot.name))
                GIT_COMMITTER_EMAIL: ((bot.email))
                GIT_AUTHOR_NAME: ((bot.name))
                GIT_AUTHOR_EMAIL: ((bot.email))
                GPG_SIGNING_PRIVATE_KEY: ((gpg.signing_private_key))
                GPG_SIGNING_PRIVATE_PASSWORD: ((gpg.signing_private_password))
            - put: tap-repo
              params:
                repository: tap-repo
                rebase: true
              get_params:
                skip_download: true
      - task: yamlfix-check
        file: task/concourse/tasks/yamlfix/diff.yaml
        input_mapping:
          src: tap-repo
        on_failure:
          do:
            - task: yamlfix-fix
              file: task/concourse/tasks/yamlfix/write.yaml
              input_mapping:
                src: tap-repo
              output_mapping:
                src: tap-repo
            - task: git-commit
              file: task/concourse/tasks/git/commit.yaml
              input_mapping:
                src: tap-repo
              output_mapping:
                src: tap-repo
              params:
                ADD: .
                MESSAGE: 'style(yaml): apply auto-fixes'
                GIT_COMMITTER_NAME: ((bot.name))
                GIT_COMMITTER_EMAIL: ((bot.email))
                GIT_AUTHOR_NAME: ((bot.name))
                GIT_AUTHOR_EMAIL: ((bot.email))
                GPG_SIGNING_PRIVATE_KEY: ((gpg.signing_private_key))
                GPG_SIGNING_PRIVATE_PASSWORD: ((gpg.signing_private_password))
            - put: tap-repo
              params:
                repository: tap-repo
                rebase: true
              get_params:
                skip_download: true
# -----------------------------------------------------------------------------
# Resources
# -----------------------------------------------------------------------------
resources:
  - name: tap-repo
    type: git
    icon: git
    check_every: 24h
    source:
      uri: ((git.uri))
      branch: ((git.branch))
      private_key: ((vault:git.private_key))
    webhook_token: ((vault:webhook.token))
  - name: daily
    type: time
    icon: clock
    source:
      interval: 24h
  - name: task
    type: git
    icon: git
    check_every: 24h
    source:
      uri: ssh://git@codeberg.org/PurpleBooth/common-pipelines.git
      branch: main
      private_key: ((vault:git.private_key))
      git_config:
        - name: user.name
          value: Solace System Renovate Fox [bot]
        - name: user.email
          value: solace-system-renovate-fox@example.com
    webhook_token: ((vault:webhook.token))
