name: Publish and commit bottles on schedule

on:
  workflow_dispatch:
  schedule:
    # Once every hour
    - cron: '*/60 * * * *'

env:
  HOMEBREW_COLOR: 1
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1

jobs:
  autopublish:
    if: github.repository == 'PurpleBooth/homebrew-repo'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run automerge
        env:
          COMMITTER_TOKEN: ${{secrets.COMMITTER_TOKEN}}
        run: brew pr-automerge --verbose --with-label bottles --without-approval --publish --tap purplebooth/repo
