name: Add bottles
on:
  push:
    branches: main
jobs:
  bottle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Fix for https://github.com/Homebrew/linuxbrew-core/issues/20914
        run: sudo ln -s /usr/include/locale.h /usr/include/xlocale.h
        if: runner.os == 'Linux'

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Build missing bottles
        env:
          REPOSITORY_NAME: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}
          HOMEBREW_BINTRAY_KEY: "${{ secrets.HOMEBREW_BINTRAY_KEY }}"
          HOMEBREW_BINTRAY_USER: purplebooth
          BINTRAY_DL_URL: https://dl.bintray.com/purplebooth/bottles-repo
          BINTRAY_ORG: purplebooth
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        shell: bash
        run: |
          HOMEBREW_PREFIX="$(brew --repo)/Library/Taps/purplebooth/homebrew-repo/Formula/"
          git config --global user.email "temporary@example.com"
          git config --global user.name "Reset when we sign commits"

          for PACKAGE in $( grep -L "bottle" "$HOMEBREW_PREFIX"*.rb  | rev | cut -c 4- | rev | cut -c $(( ${#HOMEBREW_PREFIX} + 1 ))- ) ; do
            brew test-bot \
              --skip-setup \
              --bintray-org="$BINTRAY_ORG" \
              --root-url="$BINTRAY_DL_URL" \
              --tap=purplebooth/repo \
              --git-name="$(git config --get user.name)" \
              --git-email="$(git config --get user.email)" \
              "purplebooth/repo/$PACKAGE"
            brew test-bot \
              --ci-upload \
              --bintray-org="$BINTRAY_ORG" \
              --root-url="$BINTRAY_DL_URL" \
              --tap=purplebooth/repo \
              --git-name="$(git config --get user.name)" \
              --git-email="$(git config --get user.email)" \
              --publish \
              "purplebooth/repo/$PACKAGE" || true
          done

      - name: Add back dependencies that test-bot removes
        env:
          OS: ${{ matrix.os }}
        run: |
          brew install gpg gh

      - uses: actions/checkout@v2.3.2
        name: Checkout this repository
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.SIGNING_KEY_PRIV }}
          PASSPHRASE: ${{ secrets.SIGNING_KEY_PASS }}

      - name: Merge Homebrew's Bottle Commits
        env:
          OS: ${{ matrix.os }}
        run: |
          git fetch origin
          git switch -c "bottles-$OS-$(git rev-parse --short HEAD)"
          git remote add homebrew "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"
          git fetch homebrew
          git merge homebrew/main

      - name: Sign commits
        env:
          OS: ${{ matrix.os }}
        run: git rebase --exec 'git commit --amend --reset-author --no-edit --gpg-sign' origin/main
      - name: Create GH Config
        shell: bash
        run: |
          mkdir -p $HOME/.config/gh/
          cat > $HOME/.config/gh/hosts.yml <<EOF
          github.com:
             user: "$GH_USERNAME"
             oauth_token: "$GITHUB_TOKEN"
          EOF
        env:
          GH_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      - name: Create bottle PR
        env:
          OS: ${{ matrix.os }}
        run: |
          gh pr create -l bottles --fill
