name: brew test-bot
on:
  push:
    branches: main
jobs:
  test-bot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Build missing bottles
        env:
          REPOSITORY_NAME: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}
          HOMEBREW_BINTRAY_KEY: "${{ secrets.HOMEBREW_BINTRAY_KEY }}"
          HOMEBREW_BINTRAY_USER: purplebooth
          BINTRAY_DL_URL: https://dl.bintray.com/purplebooth/bottles-repo
          BINTRAY_ORG: purplebooth
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        shell: bash
        run: |
          cd "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"
          for PACKAGE in $( "grep -L "bottle" Formula/*.rb  | rev | cut -c 4- | rev | cut -c 9-" ) ; do
            brew test-bot \
              --ci-upload \
              --bintray-org="$BINTRAY_ORG" \
              --root-url="$BINTRAY_DL_URL" \
              --tap=purplebooth/repo \
              --git-name="$GITHUB_ACTOR" \
              --git-email="$GITHUB_ACTOR@users.noreply.github.com" \
              --publish \
              "purplebooth/repo/$PACKAGE"

            git switch -c "$PACKAGE-$(git rev-parse --short HEAD)"
            gh pr create -l bottles --fill
            git switch main
            git reset --hard origin/main
          done
