name: Test Repo

on:
  push: ~
  pull_request: ~

jobs:
  audit:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - run: mkdir -p "$(brew --repo)/Library/Taps/purplebooth"
    - run: cp -r ./. "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"

    - run: |
        set -euo pipefail
        
        for I in Formula/*.rb; do 
          brew  test "purplebooth/repo/$(echo "$I"  | sed -e 's/^Formula\/*//' | sed -e 's/.rb$//')"   
        done

