on:
  push: ~
  pull_request: ~

jobs:
  bottle:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Cache Directory
      id: get-cache-dir
      run: |
        echo "::set-output name=dir::$(brew --cache)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.get-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.rb') }}
    - run: mkdir -p "$(brew --repo)/Library/Taps/purplebooth"
    - run: cp -r ./. "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"
    - shell: bash
      run: |
        set -euo pipefail
        
        for I in Formula/*.rb; do
          brew test-bot \
            --ci-upload \
            --bintray-org=purplebooth \
            --root-url=https://dl.bintray.com/purplebooth/bottles-repo \
            --tap purplebooth/repo \
            "purplebooth/repo/$(echo "$I"  | sed -e 's/^Formula\/*//' | sed -e 's/.rb$//')"
        done
      env:
        HOMEBREW_BINTRAY_USER: purplebooth
        HOMEBREW_BINTRAY_KEY: '${{ secrets.HOMEBREW_BINTRAY_KEY }}'

