name: Audit Repo

on:
  push: ~
  pull_request: ~

jobs:
  audit:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p "$(brew --repo)/Library/Taps/purplebooth"
    - run: cp -r ./. "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"
    - run: |
        set -euo pipefail
        
        for I in Formula/*.rb; do 
          brew  audit --strict --online --new-formula "purplebooth/repo/$(echo "$I"  | sed -e 's/^Formula\/*//' | sed -e 's/.rb$//')"   
        done


