on:
  push: ~
  pull_request: ~

jobs:
  audit:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Cache Details
        id: get-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
          ls -R > /tmp/hash
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('/tmp/hash') }}
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/audit-all.sh
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Cache Details
        id: get-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
          ls -R > /tmp/hash
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('/tmp/hash') }}
      - run: ./bin/install-dependencies.sh
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/install-all.sh
      - run: ./bin/test-all.sh
  bottle:
    needs:
      - audit
      - test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Cache Details
        id: get-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
          ls -R > /tmp/hash
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('/tmp/hash') }}
      - shell: bash
        run: ./bin/install-dependencies.sh
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/bottle-all.sh
        env:
          BINTRAY_API_URL: https://api.bintray.com
          BINTRAY_DL_URL: https://dl.bintray.com/purplebooth/bottles-repo
          BINTRAY_ORG: purplebooth
          HOMEBREW_BINTRAY_USER: purplebooth
          HOMEBREW_BINTRAY_KEY: '${{ secrets.HOMEBREW_BINTRAY_KEY }}'
      - run: |
          cd "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"
          git pull --rebase
          git push

