on:
  push: ~
  pull_request: ~

jobs:
  audit:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - id: get-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
          ls -R > /tmp/hash
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('/tmp/hash') }}
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/audit-all.sh
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
          ls -R > /tmp/hash
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('/tmp/hash') }}
      - run: ./bin/install-dependencies.sh
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/install-all.sh
      - run: ./bin/test-all.sh

