on:
  push: ~
  pull_request: ~

jobs:
  audit:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Cache Directory
        id: get-cache-dir
        run: |
          echo "::set-output name=dir::$(brew --cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.rb') }}
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/audit-all.sh
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Cache Directory
        id: get-cache-dir
        run: |
          echo "::set-output name=dir::$(brew --cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.rb') }}
      - run: ./bin/install-dependencies.sh
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/install-all.sh
      - run: ./bin/test-all.sh
  bottle:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Cache Directory
        id: get-cache-dir
        run: |
          echo "::set-output name=dir::$(brew --cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.rb') }}
      - shell: bash
        run: ./bin/install-dependencies.sh
      - run: ./bin/tap-without-clone.sh
      - run: ./bin/bottle-all.sh
        env:
          BINTRAY_API_URL: https://api.bintray.com
          BINTRAY_DL_URL: https://dl.bintray.com/purplebooth/bottles-repo
          BINTRAY_ORG: purplebooth
          HOMEBREW_BINTRAY_USER: purplebooth
          HOMEBREW_BINTRAY_KEY: '${{ secrets.HOMEBREW_BINTRAY_KEY }}'


