name: Publish and commit bottles

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true

env:
  HOMEBREW_COLOR: 1
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment once started
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.COMMITTER_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ':shipit: @${{github.actor}} has [triggered a merge](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot_body: ':robot: A scheduled task has [triggered a merge](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot: BrewTestBot

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          COMMITTER_TOKEN: ${{secrets.COMMITTER_TOKEN}}
          HOMEBREW_BINTRAY_USER: purplebooth
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        run: brew pr-pull --debug ${{github.event.inputs.pull_request}} --tap purplebooth/repo

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{secrets.COMMITTER_TOKEN}}

      - name: Post comment on failure
        if: ${{!success()}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.COMMITTER_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ':warning: @${{github.actor}} bottle publish [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot_body: ':warning: Bottle publish [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot: BrewTestBot

      - name: Dismiss approvals on failure
        if: ${{!success()}}
        uses: Homebrew/actions/dismiss-approvals@master
        with:
          token: ${{secrets.COMMITTER_TOKEN}}
          pr: ${{github.event.inputs.pull_request}}
          message: 'bottle publish failed'
